"""init

Revision ID: 14cae24ee07c
Revises:
Create Date: 2026-03-15 19:29:53.933390

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "14cae24ee07c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "price",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("ticker", sa.String(length=50), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("price", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_price_ticker"), ["ticker"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_price_timestamp"), ["timestamp"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("price", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_price_timestamp"))
        batch_op.drop_index(batch_op.f("ix_price_ticker"))

    op.drop_table("price")
    # ### end Alembic commands ###
